groups:
- name: recording-rules
  interval: 30s
  rules:
    - record: instance:cpu_usage_percent:avg5m
      expr: |
        100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

    - record: app:rps:sum1m
      expr: sum by (instance) (rate(app_http_requests_total[1m]))

    - record: app:error_rate_5xx:sum5m
      expr: sum by (instance) (rate(app_http_requests_total{code=~"5.."}[5m]))

    - record: app:latency_p95_seconds:by_instance
      expr: |
        histogram_quantile(
          0.95,
          sum by (le, instance) (rate(app_request_duration_seconds_bucket[5m]))
        )
